language: node_js
node_js:
- '0.12'

env:
  global:
  - GH_REF=github.com/climatescope/climatescope.github.io.git
  - DEPLOY_BRANCH=master
  - secure: "Z159wfAlqF9wjKIQidjYCECUMQb3SvB5IvpaKKsXXx0ghd6KAfH/74BGrgOHcPWu67mqKOSGdqQDe2RZ3A3WA8f1aPwT+1Qw6OeaIxWD8eMTL58gEhY68PlhnTUvY+QwV7ufxxi/gZGltvM/1+X3nA12hzyfV/Tn+gqrpEMEUmM="

before_install:
- chmod +x ./.build_scripts/deploy.sh

script:
- gulp stage

after_success:
- ./.build_scripts/deploy.sh