safe:           false

# Domain and path_prefix are neede for IE9 CORS.
# More in: https://github.com/flipside-org/climatescope/issues/221
domain:         http://localhost:4000
path_prefix:    
#domain:         http://demo.flipside.org
#path_prefix:    /climatescope

# Address of climatescope's proxy server.
pdbproxy:       http://pdbproxy.global-climatescope.org 

name:
  en:           Climatescope
  es:           Climascopio
description:
  en:           The Climatescope a unique country-by-country assessment, interactive report and index that evaluates the investment climate for climate-related investment worldwide.
  es:           El Climascopio es un análisis a fondo de 55 países a nivel mundial y un informe e índice interactivo que evalúa el clima de inversión para las energías limpias.
keywords:
  en:           Climatescope, Clean Energy, Investment, Latin America and the Caribbean, Climate Change, Investment Climate, Green Economy, Greenhouse Gas Management, Carbon Management, Clean Energy, Low-Carbon Business, Value Chain, Renewables, Climate Financing, Multilateral Investment Fund, Inter-American Development Bank, Bloomberg New Energy Finance, DfiD, Power Africa
  es:           Climascopio, Energía Limpia, Inversion, América Latina y el Caribe, Cambio Climático, Clima de Inversión, Economía Verde, Gestión Gases de Efecto Invernadero, Negocios de Bajo Carbono, Energía Limpia, Cadenas de Valor, Financiamiento Climático, Renovables, Fondo Multilateral de Inversiones, Banco Interamericano de Desarrollo, Bloomberg New Energy Finance, DfiD, Power Africa
edition:        2014
exclude:        ['node_modules', 'source_assets', 'Gruntfile.js', 'package.json', 'README.md']
collections:
  en_region:
    output: true
    permalink: /en/region/:path/
    lang: en
    i18n:
      en: en_region
      es: es_region
    
  es_region:
    output: true
    permalink: /es/region/:path/
    lang: es
    i18n:
      en: en_region
      es: es_region
      
  en_country:
    output: true
    permalink: /en/country/:path/
    lang: en
    i18n:
      en: en_country
      es: es_country
      
  es_country:
    output: true
    permalink: /es/pais/:path/
    lang: es
    i18n:
      en: en_country
      es: es_country
      
  en_state:
    output: true
    permalink: /en/country/:path/
    lang: en
    i18n:
      en: en_state
      es: es_state
      
  es_state:
    output: true
    permalink: /es/pais/:path/
    lang: es
    i18n:
      en: en_state
      es: es_state
      
  en_parameter:
    output: true
    permalink: /en/topic/:path/
    lang: en
    i18n:
      en: en_parameter
      es: es_parameter
      
  es_parameter:
    output: true
    permalink: /es/tema/:path/
    lang: es
    i18n:
      en: en_parameter
      es: es_parameter

  en_page:
    output: true
    permalink: /en/:path/
    lang: en
    i18n:
      en: en_page
      es: es_page
      
  es_page:
    output: true
    permalink: /es/:path/
    lang: es
    i18n:
      en: en_page
      es: es_page
