source: app
exclude:
  - assets/scripts
  - assets/styles
  - assets/icons
baseurl: https://global-climatescope.org

appTitle: 'Climatescope'
appEdition: 2019
appDescription: 'Climatescope is a unique country-by-country assessment, interactive report and index that evaluates the investment conditions for clean energy in emerging markets.'

kramdown:
  input: GFM
  syntax_highlighter: rouge

# SEO defaults:
# Everything is handled through javascript. Check assets/scripts/config

collections:
  pages:
    output: true
  
  library:
    output: true
# Define defaults for the different CTs of the library

defaults:
  - 
    scope:
      path: "_library/insights"
    values:
      type: "insight"
  - 
    scope:
      path: "_library/updates"
    values:
      type: "update"
  - 
    scope:
      path: "_library/off-grid"
    values:
      type: "off-grid"