source: app
exclude:
  - assets/scripts
  - assets/styles
  - assets/icons
baseurl: //global-climatescope.org

appTitle: 'Climatescope'
appEdition: 2018
appDescription: 'Climatescope is a unique country-by-country assessment, interactive report and index that evaluates the investment conditions for clean energy in emerging markets.'

kramdown:
  input: GFM
  syntax_highlighter: rouge

# SEO defaults:
# Everything is handled through javascript. Check assets/scripts/config

collections:
  pages:
    output: true