# https://github.com/developmentseed/how/issues/149
# ssh-keygen -m pem -t rsa -b 4096 -C climatescope/climatescope.org -f deploy_key

# YAML anchors for base definitions
base_def: &base_def
  docker:
    - image: developmentseed/developmentseed.org:slim
  working_directory: ~/repo
  environment:
    # Dev and Prod branches set in the workflows section. 
    # - DEVELOPMENT_BRANCH: v2019
    # - PRODUCTION_BRANCH: master
    - GH_REF: git@github.com:climatescope/climatescope.org.git
    - GH_NAME: "Development Seed"
    - GH_EMAIL: "dev@developmentseed.org"

restore_cache_def: &restore_cache_def
  # Download and cache dependencies
  keys:
  - v1-dependencies-{{ checksum "package.json" }}
  - v1-dependencies-  # fallback if checksum fails

##
## START Circle CI configuration
##

version: 2.1
jobs:
  prepare:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn lint
  test:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn test
  build:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: 
          name: Build app
          command: |
            yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
              - _site/*
  build-stage:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: 
          name: Build app
          command: |
            yarn build-stage
      - persist_to_workspace:
          root: ~/repo
          paths:
              - _site/*
  deploy-surge:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to surge
          command: |
            cp /workspace/_site/index.html /workspace/_site/200.html
            ./node_modules/surge/lib/cli.js --project /workspace/_site --domain climatescope.surge.sh
  deploy-gh:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - add_ssh_keys:
          fingerprints:
            - "d8:2c:2c:13:f8:dd:60:d2:e4:df:de:90:f8:55:d5:4c"
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to GH Pages
          command: |
            cd /workspace/_site
            git init
            git config user.name "$GH_NAME"
            git config user.email "$GH_EMAIL"
            git add .
            git commit -m "CI deploy [skip ci]"
            git remote add origin $GH_REF
            git push origin --force --quiet HEAD:gh-pages
            rm -rf .git
    
workflows:
  version: 2
  main:
    jobs:
      # These jobs will always run to ensure a proper build.
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      # Deployment jobs run according to the branch.
      - build-stage:
          requires:
            - prepare
          filters:
            branches:
              only: v2019
      - deploy-surge:
          requires:
            - lint
            - test
            - build-stage
          filters:
            branches:
              only: v2019
      - deploy-gh:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only: master
